development:
  adapter: postgresql
  encoding: unicode
  database: yelp2_development
  pool: 5
  username: vagrant
  password: vagrant


test:
  adapter: postgresql
  encoding: unicode
  database: yelp2_test
  pool: 5
  username: vagrant
  password: vagrant
